### ISSUE TITLE
Profile: Visible HTML when list visibility is checked 

### ISSUE THREAD

**Issue by ocean90** [wearerequired/rplus-wp-team-list#31] opened 2017-01-13 15:01 UTC
<img width="724" alt="bildschirmfoto 2017-01-13 um 16 00 16" src="https://cloud.githubusercontent.com/assets/617637/21934356/6471717a-d9a9-11e6-989c-55abd18aba3f.png">

**Comment by swissspidy** [comment] 2017-01-13 15:08
Duplicate of #26.

We should really make a new release here.

**Closed by swissspidy** 2017-01-13 15:08 UTC
Labels: bug
